apiVersion: apps/v1
kind: Deployment
metadata:
  name: polarstomps
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: polarstomps
  template:
    metadata:
      labels:
        app: polarstomps
    spec:
      volumes:
      containers:
        - image: howdoicomputer/polarstomps:v10
          imagePullPolicy: IfNotPresent
          name: polarstomps
          ports:
            - name: polarstomps
              containerPort: 8080
              protocol: TCP
          ports:
            - name: monitoring
              containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "512m"
