apiVersion: apps/v1
kind: Deployment
metadata:
  name: polarstomps
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: polarstomps
  template:
    metadata:
      labels:
        app: polarstomps
    spec:
      nodeSelectors:
        cloud.google.com/compute-class: "Scale-Out"
      containers:
        - name: polarstomps
          image: howdoicomputer/polarstomps:v18
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: auth
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: "redis"
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: "redis"
                  key: redis_port
          ports:
            - name: polarstomps
              containerPort: 8080
              protocol: TCP
          ports:
            - name: monitoring
              containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "100MiB"
