apiVersion: v1
kind: Service
metadata:
  name: polarstomps
  namespace: polarstomps
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: polarstomps
