apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: polarstomps-metrics
spec:
  selector:
    matchLabels:
      app: polarstomps
  # This makes it so that a Prometheus configuration is generated to scrape
  # the metrics endpoint.
  #
  endpoints:
  - port: metrics
    interval: 30s
