apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: polarstomps-metrics
spec:
  selector:
    matchLabels:
      app: polarstomps
  endpoints:
  - port: polarstomps
    interval: 30s
