apiVersion: apps/v1
kind: Deployment
metadata:
  name: polarstomps
  app.kubernetes.io/name: polarstomps
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: polarstomps
      app.kubernetes.io/name: polarstomps
  template:
    metadata:
      labels:
        app: polarstomps
        app.kubernetes.io/name: polarstomps
    spec:
      volumes:
      containers:
        - image: howdoicomputer/polarstomps:v8
          imagePullPolicy: IfNotPresent
          name: polarstomps
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "512m"
