apiVersion: v1
kind: Service
metadata:
  name: polarstomps
  namespace: polarstomps
  annotations:
    # This annotation allows for GCP to associate a generated
    # BackendConfig with the generated classic load balancer.
    #
    # The BackendConfig itself is specified in healthcheck.yml
    #
    beta.cloud.google.com/backend-config: '{"default": "polarstomps"}'
spec:
  type: NodePort
  ports:
    - name: polarstomps
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: monitoring
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: polarstomps
