apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polarstomps-ingress
  namespace: polarstomps
  annotations:
    kubernetes.io/ingress.global-static-ip-name: infra-prod-polarstomps-addr
    networking.gke.io/managed-certificates: infra-prod-polarstomps-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: polarstomps
      port:
        number: 8080
