apiVersion: apps/v1
kind: Deployment
metadata:
  name: polarstomps
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: polarstomps
  template:
    metadata:
      labels:
        app: polarstomps
    spec:
      serviceAccountName: polarstomps
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      containers:
        - name: polarstomps
          image: howdoicomputer/polarstomps:v22
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: auth
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: "redis"
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: "redis"
                  key: redis_port
            - name: GCS_EXAMPLE_BUCKET_NAME
              value: "infra-prod-example"
          ports:
            - name: polarstomps
              containerPort: 8080
              protocol: TCP
          ports:
            - name: monitoring
              containerPort: 9090
              protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              cpu: 250m
              memory: 1Gi
              ephemeral-storage: 10Mi
