apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: polarstomps-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: polarstomp
  endpoints:
  - port: metrics
    interval: 30s
